apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: tailscale-node-controller
build:
  artifacts:
    - image: ghcr.io/samcday/tailscale-node-controller
      docker:
        dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: tailscale-node-controller
        chartPath: chart
        valuesFiles:
          - chart/values.yaml
