{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tailscale-node-controller.fullname" . }}
  labels:
    {{- include "tailscale-node-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, watch, list]
  - apiGroups: [""]
    resources: [events]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tailscale-node-controller.fullname" . }}
  labels:
    {{- include "tailscale-node-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tailscale-node-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "tailscale-node-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
